### ISSUE TITLE
Command not found and NMAP scan not initiated

### ISSUE THREAD

**Issue by justanothertechie** [ShivamRai2003/Reconky-Automated_Bash_Script#2]
![image](https://user-images.githubusercontent.com/59411240/127103545-db9d7cc3-9574-418f-8f4e-96e95d9379a5.png)

![image](https://user-images.githubusercontent.com/59411240/127103508-189bfbad-c526-47d5-9c6b-e173bee1d0f6.png)

Subdomain enumeration did happen but few commands and nmap did not get executed.

**Comment by ShivamRai2003** [comment]
Hi, nmap will not initiate  until it will get live subdomains. since httpobe didn't ran on live subdomains. that's why the nmap didn't run.
Solution : just install the install.sh script and verify the each tool like knockpy or httprobe or waybackurls can be globally executed means from any directory it should be accessible !.

Always make sure you take snapshots so you can revert easily.

**Comment by justanothertechie** [comment]
I did install using `chmod +x install.sh` but I am unable to execute the individual tools

**Comment by ShivamRai2003** [comment]
chmod +x install.sh is used to give permission basically to run use ./install.sh. all tools will be executed automatically.
you are unable to execute because due to the directory problem.so kindly use  fresh kali image or pref to download kali linux 2021.2 live image. and then run the install.sh. cheers !
